name: HTML Presubmit

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install npm packages
        run: npm install
      - name: Lint
        # Run HTMLLint on diffed HTML files. Do not run if there are no diffs.
        run: git diff --diff-filter=ACM --name-only origin/master HEAD -- . ':!node_modules' | grep -E "(.*)\.(htm|html)$" | xargs --no-run-if-empty npx htmllint
